---
codecov:
  branch: python
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 0
  round: down
  range: "70...100"

  status:
    project:
      default: false
      integration_tests:
        paths:
          - testsuite/python/
        enabled: yes
        threshold: 1%
      unit_tests:
        paths:
          - "src/**/*tests/"
        enabled: yes
        threshold: 1%
      core:
        paths:
          - "src/"
          - "!src/**/*tests/"
          - "!src/python/"
        enabled: yes
        threshold: 1%
    patch:
      default:
        enabled: yes
        threshold: 1%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false

ignore:
  - "libs"
  - "doc/tutorials"
  - "samples"
  - "maintainer"
  - "src/walberla_bridge/**/generated_kernels/*"
  - "src/walberla_bridge/myintrin.h"
  - "src/walberla_bridge/philox_rand.h"
