image: ghcr.io/espressomd/docker/ubuntu-20.04:254edd4a9c6e4d7b557be73158e400f5794e4f99

stages:
  - prepare
  - build
  - additional_checks
  - result

.global_job_template: &global_job_definition
  except:
    - staging.tmp
    - trying.tmp
  timeout: 1h
  interruptible: true

.notification_job_template: &notification_job_definition
  <<: *global_job_definition
  variables:
    GIT_SUBMODULE_STRATEGY: none
  dependencies: []
  timeout: 40m
  interruptible: false
  tags:
    - linux

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CCACHE_DIR: /cache
  CCACHE_MAXSIZE: 100G
  with_ccache: "true"

status_pending:
  <<: *notification_job_definition
  stage: prepare
  script: sh maintainer/gh_post_status.sh pending

maxset-walberla:
  <<: *global_job_definition
  stage: build
  variables:
     with_cuda: 'false'
     myconfig: 'maxset'
     with_coverage: 'true'
     with_walberla: 'true'
     with_scafacos: 'false'
     with_stokesian_dynamics: 'false'
     check_skip_long: 'true'
     check_procs: '8'
     build_procs: '4'
     make_check_unit_tests: 'false'
  script:
    - bash maintainer/CI/build_cmake.sh
  tags:
    - docker
    - linux
    - numa

status_success:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_post_status.sh success
  when: on_success

status_failure:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_post_status.sh failure
  when: on_failure

notify_success:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_close_issue.sh
  when: on_success
  only:
    - python

notify_failure:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_create_issue.sh
  when: on_failure
  only:
    - python
