/*
 * Copyright (C) 2019-2026 The ESPResSo project
 *
 * This file is part of ESPResSo.
 *
 * ESPResSo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ESPResSo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

/**
 * @file
 * @ref walberla::LBWalberlaImplColorGradient implements the interface of the
 * two-component color-gradient LB waLBerla bridge using sweeps generated by
 * lbmpy (see <tt>maintainer/walberla_kernels</tt>).
 */

#include "LBWalberlaCommon.hpp"

#include <blockforest/Initialization.h>
#include <blockforest/StructuredBlockForest.h>
#include <domain_decomposition/BlockDataID.h>
#include <domain_decomposition/IBlock.h>
#include <field/AddToStorage.h>
#include <field/vtk/FlagFieldCellFilter.h>
#include <field/vtk/VTKWriter.h>
#include <stencil/D3Q19.h>
#include <stencil/D3Q27.h>
#include <waLBerlaDefinitions.h>
#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
#include <gpu/AddGPUFieldToStorage.h>
#include <gpu/HostFieldAllocator.h>
#endif

#include "../BoundaryHandling.hpp"
#include "../BoundaryPackInfo.hpp"
#include "../utils/boundary.hpp"
#include "../utils/types_conversion.hpp"
#include "InterpolateAndShiftAtBoundary.hpp"
#include "ResetForce.hpp"
#include "lb_fields.hpp"
#include "lb_kernels.hpp"
#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
#include "lb_fields.cuh"
#include "lb_kernels.cuh"
#endif

#include <walberla_bridge/Architecture.hpp>
#include <walberla_bridge/BlockAndCell.hpp>
#include <walberla_bridge/LatticeWalberla.hpp>
#include <walberla_bridge/lattice_boltzmann/LBWalberlaBase.hpp>
#include <walberla_bridge/lattice_boltzmann/LBWalberlaColorGradientBase.hpp>
#include <walberla_bridge/lattice_boltzmann/LeesEdwardsPack.hpp>
#include <walberla_bridge/utils/ResourceManager.hpp>
#include <walberla_bridge/walberla_init.hpp>

#include <utils/Vector.hpp>

#include <array>
#include <bitset>
#include <cstddef>
#include <functional>
#include <initializer_list>
#include <limits>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

namespace walberla {

/** @brief Class that runs and controls the two-component color-gradient LB on
 * waLBerla. */
template <typename FloatType, lbmpy::Arch Architecture>
class LBWalberlaImplColorGradient
    : public LBWalberlaCommon<
          LBWalberlaImplColorGradient<FloatType, Architecture>, FloatType,
          Architecture>,
      public virtual LBWalberlaColorGradientBase {
  using Base =
      LBWalberlaCommon<LBWalberlaImplColorGradient<FloatType, Architecture>,
                       FloatType, Architecture>;
  friend Base;

protected:
  // ---- Types from the mixin (re-export for the .impl.hpp files) ----
  using typename Base::_PdfField;
  using typename Base::_VectorField;
  using typename Base::BlockStorage;
  using typename Base::BoundaryFullCommunicator;
  using typename Base::BoundaryModel;
  using typename Base::GhostComm;
  using typename Base::Kernels;
  using typename Base::PDFStreamingCommunicator;
  using typename Base::RegularFullCommunicator;
  template <class Field>
  using PackInfo = typename Base::template PackInfo<Field>;

  // CollisionModel variant — used by LBWalberlaCommon CRTP methods
  // (get_rng_state / set_rng_state). The CG leaf overrides those methods to
  // throw / return nullopt, so m_collision_model is never dereferenced; but the
  // mixin bodies are still compiled and require the type to exist.
  using CollisionModel =
      std::variant<typename Kernels::StreamCollisionModelThermalized,
                   typename Kernels::StreamCollisionModelLeesEdwards>;

  using CollisionModelTwoComponent =
      typename Kernels::CollisionModelTwoComponent;
  using StreamModelTwoComponent = typename Kernels::StreamModelTwoComponent;
  using ColorGradientModel = typename Kernels::ColorGradientModel;

public:
  using typename Base::FlagField;
  using typename Base::PdfField;
  using typename Base::ScalarField;
  using typename Base::Stencil;
  using typename Base::StencilFull;
  using typename Base::VectorField;
#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
  using typename Base::GPUField;
  using typename Base::PdfFieldCpu;
  using typename Base::VectorFieldCpu;
#endif

protected:
  // ---- Pull in inherited members so unqualified names resolve ----
  using Base::add_to_storage;
  using Base::derived;
  using Base::FloatType_c;
  using Base::get_lattice;
  using Base::ghost_communication;
  using Base::make_density_interpolation_kernel;
  using Base::make_velocity_interpolation_kernel;
  using Base::zero_centered_to_lb;
  using Base::zero_centered_to_lb_in_place;
  using Base::zero_centered_to_md;
  using Base::zero_centered_to_md_in_place;

  // Data members (from Base)
  using Base::Boundary_flag;
  using Base::m_boundary;
  using Base::m_boundary_communicator;
  using Base::m_density;
  using Base::m_flag_field_id;
  using Base::m_force_to_be_applied_id;
  using Base::m_full_communicator;
  using Base::m_has_boundaries;
  using Base::m_laf_communicator;
  using Base::m_last_applied_force_field_id;
  using Base::m_lattice;
  using Base::m_mpi_cart_comm_observer;
  using Base::m_pdf_communicator;
  using Base::m_pdf_streaming_communicator;
  using Base::m_pending_ghost_comm;
  using Base::m_seed;
  using Base::m_vel_communicator;
  using Base::m_vel_tmp_field_id;
  using Base::m_velocity_field_id;
  using Base::m_zc_to_lb;
  using Base::m_zc_to_md;

protected:
  // ---- Member Variables (leaf-specific) ----

  // Physical parameters
  std::array<FloatType, 2> m_viscosity; /// kinematic viscosity (per component)
  FloatType m_sigma{}; /// interface tension coefficient (two-component)
  FloatType m_beta{};  /// interface thickness parameter (two-component)
  FloatType m_kT;

  // Block data access handles (PDF / two-component / temporaries)
  std::array<BlockDataID, 2> m_pdf_field_id;
  std::array<BlockDataID, 2> m_pdf_tmp_field_id;

  // Color gradient fields
  std::array<BlockDataID, 2> m_rho_field_id;
  BlockDataID m_phasefield_id;
  BlockDataID m_color_gradient_field_id;
  std::array<BlockDataID, 2> m_force_cg_field_id;

#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
  std::optional<BlockDataID> m_pdf_cpu_field_id;
  std::optional<BlockDataID> m_vel_cpu_field_id;
#endif

  // Color gradient communicators (CG-specific)
  std::shared_ptr<RegularFullCommunicator> m_pdf_a_communicator;
  std::shared_ptr<RegularFullCommunicator> m_pdf_b_communicator;
  std::shared_ptr<RegularFullCommunicator> m_phasefield_communicator;
  std::shared_ptr<RegularFullCommunicator> m_color_gradient_communicator;

  // Stub members required by LBWalberlaCommon CRTP bodies.
  // The CG leaf overrides the corresponding virtual methods to throw /
  // return nullopt, so these are never actually dereferenced at runtime.
  std::shared_ptr<CollisionModel> m_collision_model;
  std::shared_ptr<ResetForce<PdfField, VectorField>> m_reset_force;

  // color gradient sweeps
  std::shared_ptr<CollisionModelTwoComponent> m_collision_model_two_component;
  std::shared_ptr<StreamModelTwoComponent> m_stream_model_two_component;
  std::shared_ptr<ColorGradientModel> m_color_gradient_model;

#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
  std::shared_ptr<gpu::HostFieldAllocator<FloatType>> m_host_field_allocator;
#endif

public:
  LBWalberlaImplColorGradient(std::shared_ptr<LatticeWalberla> lattice,
                              std::vector<double> viscosity, double density,
                              bool /* two_component */)
      : Base(lattice, FloatType_c(density)),
        m_viscosity{FloatType_c(viscosity.at(0)), FloatType_c(viscosity.at(1))},
        m_kT(FloatType{0}) {

    auto const &blocks = m_lattice->get_blocks();
    auto const n_ghost_layers = m_lattice->get_ghost_layers();
    if (n_ghost_layers == 0u)
      throw std::runtime_error("At least one ghost layer must be used");

    // Initialize and register fields (must use the "underlying" types)
    m_pdf_field_id[0] = this->template add_to_storage<_PdfField>("pdfs_a");
    m_pdf_tmp_field_id[0] =
        this->template add_to_storage<_PdfField>("pdfs_a_tmp");
    m_last_applied_force_field_id =
        this->template add_to_storage<_VectorField>("force last");
    m_force_to_be_applied_id =
        this->template add_to_storage<_VectorField>("force next");
    m_velocity_field_id =
        this->template add_to_storage<_VectorField>("velocity");
    m_vel_tmp_field_id =
        this->template add_to_storage<_VectorField>("velocity_tmp");

    m_pdf_field_id[1] = this->template add_to_storage<_PdfField>("pdfs_b");
    m_pdf_tmp_field_id[1] =
        this->template add_to_storage<_PdfField>("pdfs_b_tmp");
    m_rho_field_id[0] = this->template add_to_storage<ScalarField>("rho_a");
    m_rho_field_id[1] = this->template add_to_storage<ScalarField>("rho_b");
    m_phasefield_id = this->template add_to_storage<ScalarField>("phasefield");
    m_color_gradient_field_id =
        this->template add_to_storage<_VectorField>("color_gradient");
    m_force_cg_field_id[0] =
        this->template add_to_storage<_VectorField>("force_a");
    m_force_cg_field_id[1] =
        this->template add_to_storage<_VectorField>("force_b");

#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
    m_host_field_allocator =
        std::make_shared<gpu::HostFieldAllocator<FloatType>>();
#endif

    // Initialize and register pdf field with zero centered density
    auto pdf_setter = typename Kernels::InitialPDFsSetter(
        m_force_to_be_applied_id, m_pdf_field_id[0], m_velocity_field_id, 1.0);
    for (auto &block : *blocks) {
      pdf_setter(&block);
    }

    // Initialize and register flag field (fluid/boundary)
    m_flag_field_id = field::addFlagFieldToStorage<FlagField>(
        blocks, "flag field", n_ghost_layers);
    // Initialize boundary sweep
    reset_boundary_handling(m_lattice->get_blocks());

    // Set up the communication and register fields
    setup_streaming_communicator();
    setup_full_communicator();

    m_pending_ghost_comm.set();
  }

  ~LBWalberlaImplColorGradient() override = default;

  // ---- Integration (Core LB Algorithm) ----

  void integrate() override {
    integrate_pull_scheme();
    integrate_vtk_writers();
  }

protected:
  void integrate_vtk_writers() override {
    for (auto const &it : this->m_vtk_auto) {
      auto &vtk_handle = it.second;
      if (vtk_handle->enabled) {
        vtk::writeFiles(vtk_handle->ptr)();
        vtk_handle->execution_count++;
      }
    }
  }

private:
  /**
   * @brief One LB time step using the color-gradient pull scheme.
   * Sequence: stream two-component, sync phasefield, compute color gradient,
   * sync color gradient, collide two-component, reset component forces,
   * sync PDFs.
   */
  void integrate_pull_scheme() {
    assert(m_mpi_cart_comm_observer.is_valid());
    auto const &blocks = get_lattice().get_blocks();

    // CG stream
    integrate_stream_two_component(blocks);
    // Sync phasefield
    m_phasefield_communicator->communicate();

    // Compute color gradient field
    integrate_color_gradient(blocks);
    // Sync color gradient (needed for off-lattice interpolation)
    m_color_gradient_communicator->communicate();

    // CG collision
    integrate_collide_two_component(blocks);
    // Reset component force fields (consumed by collision)
    integrate_reset_force_two_component(blocks);

    // Sync pdfs
    m_pdf_a_communicator->communicate();
    m_pdf_b_communicator->communicate();
  }

  void
  integrate_collide_two_component(std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_collision_model_two_component)(&block);
  }

  void integrate_color_gradient(std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_color_gradient_model)(&block);
  }

  void
  integrate_stream_two_component(std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_stream_model_two_component)(&block);
  }

  void integrate_reset_force_two_component(
      std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks) {
      auto force_a =
          block.template getData<VectorField>(m_force_cg_field_id[0]);
      auto force_b =
          block.template getData<VectorField>(m_force_cg_field_id[1]);
      lbm::accessor::Vector::initialize(force_a, Vector3<FloatType>{0});
      lbm::accessor::Vector::initialize(force_b, Vector3<FloatType>{0});
    }
  }

private:
  // ---- Relaxation Rate Helpers ----

  /** @brief Relaxation rate omega from kinematic viscosity: 2/(6*nu+1). */
  FloatType shear_mode_relaxation_rate(std::size_t component = 0u) const;
  /**
   * @brief Odd-mode relaxation rate for the magic parameter relation.
   * Ensures optimal bounce-back wall location for the two-relaxation-time
   * model. Default magic number is 3/16.
   */
  FloatType odd_mode_relaxation_rate(
      FloatType shear_relaxation,
      FloatType magic_number = FloatType{3} / FloatType{16}) const;

public:
  // ---- SC-only collision models: always throw ----

  void set_collision_model(double kT, unsigned int /* seed */) override {
    if (kT != 0.) {
      throw std::runtime_error(
          "thermalized collision is not supported on the color-gradient LB "
          "model");
    }
    // kT == 0: no-op, CG is inherently unthermalized
  }
  void set_collision_model(
      std::unique_ptr<LeesEdwardsPack> && /* lees_edwards_pack */) override {
    throw std::runtime_error(
        "Lees-Edwards is not supported on the color-gradient LB model");
  }
  void check_lebc(unsigned int /* shear_direction */,
                  unsigned int /* shear_plane_normal */) const override {
    // No Lees-Edwards callbacks in CG — nothing to check.
  }

  // ---- Two Component Model ----

  [[nodiscard]] bool has_two_components() const noexcept override {
    return true;
  }

  void set_collision_model_color_gradient(double sigma, double beta) override {
    m_sigma = FloatType_c(sigma);
    m_beta = FloatType_c(beta);

    // Compute relaxation rates from viscosities: omega = 2/(6*nu + 1)
    auto const omega_a = shear_mode_relaxation_rate(0u);
    auto const omega_odd_a = odd_mode_relaxation_rate(omega_a);
    auto const omega_b = shear_mode_relaxation_rate(1u);
    auto const omega_odd_b = odd_mode_relaxation_rate(omega_b);

    // Instantiate color gradient kernel
    m_color_gradient_model = std::make_shared<ColorGradientModel>(
        m_color_gradient_field_id, m_phasefield_id);

    // Instantiate collide kernel
    m_collision_model_two_component =
        std::make_shared<CollisionModelTwoComponent>(
            m_color_gradient_field_id, m_force_cg_field_id[0],
            m_force_cg_field_id[1], m_pdf_field_id[0], m_pdf_field_id[1],
            m_phasefield_id, m_rho_field_id[0], m_rho_field_id[1],
            m_velocity_field_id,
            m_beta,                   // beta (interface thickness)
            omega_a, omega_b,         // omega_even
            omega_odd_a, omega_odd_b, // omega_odd
            omega_a, omega_b,         // omega_shear
            m_sigma                   // sigma (interface tension)
        );

    // Instantiate stream kernel
    m_stream_model_two_component = std::make_shared<StreamModelTwoComponent>(
        m_force_cg_field_id[0], m_force_cg_field_id[1], m_pdf_field_id[0],
        m_pdf_field_id[1], m_phasefield_id, m_rho_field_id[0],
        m_rho_field_id[1], m_velocity_field_id);

    // Set up CG-specific communicators
    setup_communicators_two_component();
  }

  void setup_communicators_two_component() {
    auto const &blocks = m_lattice->get_blocks();

    // PDF communicators for both components (D3Q27 for full ghost layer update)
    m_pdf_a_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_pdf_a_communicator->addPackInfo(
        std::make_shared<PackInfo<PdfField>>(m_pdf_field_id[0]));

    m_pdf_b_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_pdf_b_communicator->addPackInfo(
        std::make_shared<PackInfo<PdfField>>(m_pdf_field_id[1]));

    // Phasefield communicator (D3Q27 — color gradient reads D3Q27 neighbors)
    m_phasefield_communicator =
        std::make_shared<RegularFullCommunicator>(blocks);
    m_phasefield_communicator->addPackInfo(
        std::make_shared<PackInfo<ScalarField>>(m_phasefield_id));

    // Color gradient communicator (needed for B-spline interpolation of
    // solvation force)
    m_color_gradient_communicator =
        std::make_shared<RegularFullCommunicator>(blocks);
    m_color_gradient_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_color_gradient_field_id));
  }

  void init_pdfs_from_components() override {
    auto const &blocks = m_lattice->get_blocks();
    auto init_two_component = typename Kernels::InitialPDFsSetterTwoComponent(
        m_force_cg_field_id[0], m_force_cg_field_id[1], m_pdf_field_id[0],
        m_pdf_field_id[1], m_phasefield_id, m_rho_field_id[0],
        m_rho_field_id[1], m_velocity_field_id);
    for (auto &block : *blocks) {
      init_two_component(&block);
    }
    // Communicate phasefield + PDFs after initialization
    setup_communicators_two_component(); // if not already set up
    m_phasefield_communicator->communicate();
    m_pdf_a_communicator->communicate();
    m_pdf_b_communicator->communicate();
  }

public:
  // ---- Ghost Communication ----

  /**
   * @brief Perform all pending ghost layer updates.
   * Uses a lazy scheme: ghost communications are only executed when
   * they have been marked as pending by a preceding write operation.
   */
  void ghost_communication() override {
    if (!m_pending_ghost_comm.any())
      return;
    assert(m_mpi_cart_comm_observer.is_valid());
    ghost_communication_two_component();
  }

  /** @brief Ghost communication for two-component color gradient LB. */
  void ghost_communication_two_component() {
    ghost_communication_two_component_pdf();
    ghost_communication_two_component_phasefield();
    ghost_communication_two_component_vel();
    ghost_communication_two_component_laf();
  }

  void ghost_communication_two_component_pdf() {
    if (m_pending_ghost_comm.test(GhostComm::PDF)) {
      m_pdf_a_communicator->communicate();
      m_pdf_b_communicator->communicate();
      m_pending_ghost_comm.reset(GhostComm::PDF);
    }
  }

  void ghost_communication_two_component_phasefield() {
    if (m_pending_ghost_comm.test(GhostComm::PHI)) {
      m_phasefield_communicator->communicate();
      m_pending_ghost_comm.reset(GhostComm::PHI);
    }
  }

  void ghost_communication_two_component_vel() {
    if (m_pending_ghost_comm.test(GhostComm::VEL)) {
      m_vel_communicator->communicate();
      m_pending_ghost_comm.reset(GhostComm::VEL);
    }
  }

  void ghost_communication_two_component_laf() {
    if (m_pending_ghost_comm.test(GhostComm::LAF)) {
      m_laf_communicator->communicate();
      m_pending_ghost_comm.reset(GhostComm::LAF);
    }
  }

  void ghost_communication_pdf() override {
    if (m_pending_ghost_comm.test(GhostComm::PDF)) {
      assert(m_mpi_cart_comm_observer.is_valid());
      ghost_communication_two_component_pdf();
    }
  }

  void ghost_communication_vel() override {
    if (m_pending_ghost_comm.test(GhostComm::VEL)) {
      assert(m_mpi_cart_comm_observer.is_valid());
      ghost_communication_two_component_vel();
    }
  }

  void ghost_communication_laf() override {
    if (m_pending_ghost_comm.test(GhostComm::LAF)) {
      assert(m_mpi_cart_comm_observer.is_valid());
      ghost_communication_two_component_laf();
    }
  }

  void ghost_communication_boundary() {
    if (m_pending_ghost_comm.test(GhostComm::UBB)) {
      assert(m_mpi_cart_comm_observer.is_valid());
      m_boundary_communicator->communicate();
      m_pending_ghost_comm.reset(GhostComm::UBB);
    }
  }

  /** @brief Communicate all fields at once using the D3Q27 stencil. */
  void ghost_communication_full() {
    assert(m_mpi_cart_comm_observer.is_valid());
    m_full_communicator->communicate();
    m_pending_ghost_comm.reset(GhostComm::PDF);
    m_pending_ghost_comm.reset(GhostComm::VEL);
    m_pending_ghost_comm.reset(GhostComm::LAF);
  }

public:
  // ---- Node & Slice Accessors (by quantity) ----

  // Velocity
  std::optional<Utils::Vector3d>
  get_node_velocity(Utils::Vector3i const &node,
                    bool consider_ghosts = false) const override;
  bool set_node_velocity(Utils::Vector3i const &node,
                         Utils::Vector3d const &v) override;
  std::vector<double>
  get_slice_velocity(Utils::Vector3i const &lower_corner,
                     Utils::Vector3i const &upper_corner) const override;
  void set_slice_velocity(Utils::Vector3i const &lower_corner,
                          Utils::Vector3i const &upper_corner,
                          std::vector<double> const &velocity) override;

  // Density
  std::optional<std::vector<double>>
  get_node_density(Utils::Vector3i const &node,
                   bool consider_ghosts = false) const override;
  bool set_node_density(Utils::Vector3i const &node,
                        std::vector<double> const &density) override;
  std::vector<double>
  get_slice_density(Utils::Vector3i const &lower_corner,
                    Utils::Vector3i const &upper_corner) const override;
  void set_slice_density(Utils::Vector3i const &lower_corner,
                         Utils::Vector3i const &upper_corner,
                         std::vector<double> const &density) override;

  // Population
  std::optional<std::vector<double>>
  get_node_population(Utils::Vector3i const &node,
                      bool consider_ghosts = false) const override;
  bool set_node_population(Utils::Vector3i const &node,
                           std::vector<double> const &population) override;
  std::vector<double>
  get_slice_population(Utils::Vector3i const &lower_corner,
                       Utils::Vector3i const &upper_corner) const override;
  void set_slice_population(Utils::Vector3i const &lower_corner,
                            Utils::Vector3i const &upper_corner,
                            std::vector<double> const &population) override;

  // Force
  std::optional<Utils::Vector3d>
  get_node_force_to_be_applied(Utils::Vector3i const &node) const override;
  std::optional<Utils::Vector3d>
  get_node_last_applied_force(Utils::Vector3i const &node,
                              bool consider_ghosts = false) const override;
  bool set_node_last_applied_force(Utils::Vector3i const &node,
                                   Utils::Vector3d const &force) override;
  std::vector<double> get_slice_last_applied_force(
      Utils::Vector3i const &lower_corner,
      Utils::Vector3i const &upper_corner) const override;
  void set_slice_last_applied_force(Utils::Vector3i const &lower_corner,
                                    Utils::Vector3i const &upper_corner,
                                    std::vector<double> const &force) override;

  // Pressure tensor
  std::optional<Utils::VectorXd<9>>
  get_node_pressure_tensor(Utils::Vector3i const &node) const override;
  std::vector<double>
  get_slice_pressure_tensor(Utils::Vector3i const &lower_corner,
                            Utils::Vector3i const &upper_corner) const override;

private:
  // ---- Interpolation (position-based access, leaf-specific) ----

  /** @brief Return a B-spline interpolation kernel for force distribution. */
  auto make_force_interpolation_kernel() const;
  /** @brief Return a density_weighted B-spline interpolation kernel for force
   * distribution in two component LB. */
  auto make_density_weighted_force_interpolation_kernel() const;
  /** @brief Return a B-spline interpolation kernel for solvation force
   * distribution onto fluid in two component LB. */
  auto make_solvation_force_interpolation_kernel() const;
  /** @brief Return a B-spline interpolation kernel for color gradient readout
   * in two component LB. */
  auto make_color_gradient_interpolation_kernel() const;

public:
  bool add_force_at_pos(Utils::Vector3d const &pos,
                        Utils::Vector3d const &force) override;
  void add_forces_at_pos(std::vector<Utils::Vector3d> const &pos,
                         std::vector<Utils::Vector3d> const &forces) override;
  void add_density_weighted_forces_at_pos(
      std::vector<Utils::Vector3d> const &pos,
      std::vector<Utils::Vector3d> const &forces) override;
  void
  add_solvation_forces_at_pos(std::vector<Utils::Vector3d> const &pos,
                              std::vector<double> const &delta_mus) override;

  std::vector<Utils::Vector3d>
  get_color_gradients_at_pos(std::vector<Utils::Vector3d> const &pos) override;

public:
  // ---- Boundary Handling (leaf-specific helpers) ----

  void reset_boundary_handling(std::shared_ptr<BlockStorage> const &blocks) {
    auto const [lc, uc] = m_lattice->get_local_grid_range(true);
    m_boundary = std::make_shared<BoundaryModel>(
        blocks, m_pdf_field_id[0], m_flag_field_id,
        CellInterval{to_cell(lc), to_cell(uc)});
  }

  void on_boundary_add();

public:
  // ---- Global Reductions & Physical Parameters ----

  // Global pressure tensor (always throws for CG)
  [[nodiscard]] Utils::VectorXd<9> get_pressure_tensor() const override {
    throw std::runtime_error(
        "pressure tensor not implemented for two-component LB");
  }

  // Global momentum (always throws for CG)
  [[nodiscard]] Utils::Vector3d get_momentum() const override {
    throw std::runtime_error(
        "get_momentum is not yet implemented for two-component LB");
  }

  void set_viscosity(std::vector<double> const &viscosity) override {
    m_viscosity[0] = FloatType_c(viscosity.at(0));
    if (viscosity.size() > 1) {
      m_viscosity[1] = FloatType_c(viscosity.at(1));
    }
  }

  [[nodiscard]] std::vector<double> get_viscosity() const override {
    return {static_cast<double>(m_viscosity[0]),
            static_cast<double>(m_viscosity[1])};
  }

  // ---- LBWalberlaColorGradientBase per-component accessors ----
  // Thin wrappers around the existing vector<double>-of-2 implementations.
  // A follow-up task narrows the underlying storage to array<double,2>.

  std::optional<std::array<double, 2>>
  get_node_component_densities(Utils::Vector3i const &node,
                               bool consider_ghosts = false) const override {
    auto const opt = this->get_node_density(node, consider_ghosts);
    if (!opt) {
      return std::nullopt;
    }
    auto const &vec = *opt;
    return std::array<double, 2>{vec.at(0), vec.at(1)};
  }

  bool set_node_component_densities(Utils::Vector3i const &node,
                                    std::array<double, 2> const &rho) override {
    return this->set_node_density(node, std::vector<double>{rho[0], rho[1]});
  }

  std::vector<double>
  get_slice_component_densities(Utils::Vector3i const &lower,
                                Utils::Vector3i const &upper) const override {
    return this->get_slice_density(lower, upper);
  }

  void set_component_viscosities(std::array<double, 2> const &nu) override {
    m_viscosity[0] = FloatType_c(nu[0]);
    m_viscosity[1] = FloatType_c(nu[1]);
  }

  [[nodiscard]] std::array<double, 2>
  get_component_viscosities() const override {
    return {static_cast<double>(m_viscosity[0]),
            static_cast<double>(m_viscosity[1])};
  }

  [[nodiscard]] double get_kT() const noexcept override {
    return static_cast<double>(m_kT);
  }

  // ---- External force: silently accepted but has no effect in CG ----
  // (CG forces are component-specific via m_force_cg_field_id)

  void set_external_force(Utils::Vector3d const & /* ext_force */) override {
    // No-op: color-gradient LB does not use a global external force field.
  }

  [[nodiscard]] Utils::Vector3d get_external_force() const noexcept override {
    return {};
  }

  // ---- RNG state: CG is unthermalized ----

  [[nodiscard]] std::optional<uint64_t> get_rng_state() const override {
    return std::nullopt;
  }

  void set_rng_state(uint64_t /* counter */) override {
    throw std::runtime_error("This LB instance is unthermalized");
  }

  [[nodiscard]] auto get_rho_field_id(int component) const noexcept {
    return m_rho_field_id[component];
  }

  [[nodiscard]] auto get_phasefield_id() const noexcept {
    return m_phasefield_id;
  }

  [[nodiscard]] auto get_force_cg_field_id(int component) const noexcept {
    return m_force_cg_field_id[component];
  }

  /**
   * @brief Correction factor for off-diagonal pressure tensor elements.
   * Compensates for the viscosity-dependent error in the non-equilibrium
   * stress: factor = nu / (nu + 1/6).
   */
  FloatType pressure_tensor_correction_factor() const {
    return m_viscosity[0] / (m_viscosity[0] + FloatType{1} / FloatType{6});
  }

  void pressure_tensor_correction(Matrix3<FloatType> &tensor) const {
    auto const revert_factor = pressure_tensor_correction_factor();
    for (auto const i : {1u, 2u, 3u, 5u, 6u, 7u}) {
      tensor[i] *= revert_factor;
    }
  }

  void pressure_tensor_correction(std::span<FloatType, 9ul> tensor) const {
    auto const revert_factor = pressure_tensor_correction_factor();
    for (auto const i : {1u, 2u, 3u, 5u, 6u, 7u}) {
      tensor[i] *= revert_factor;
    }
  }

public:
  // ---- File I/O ----

  void register_vtk_field_filters(walberla::vtk::VTKOutput &vtk_obj) override {
    field::FlagFieldCellFilter<FlagField> fluid_filter(m_flag_field_id);
    fluid_filter.addFlag(Boundary_flag);
    vtk_obj.addCellExclusionFilter(fluid_filter);
  }

  void register_vtk_field_writers(walberla::vtk::VTKOutput &vtk_obj,
                                  LatticeModel::units_map const &units,
                                  int flag_observables) override;

protected:
  // ---- Communicator setup (uses leaf-only PDF field IDs) ----

  /**
   * @brief Set up D3Q27 communicators for full ghost layer updates.
   * Creates per-field communicators (PDF, velocity, last-applied force)
   * as well as a combined communicator and the boundary communicator.
   */
  void setup_full_communicator() {
    auto const &blocks = m_lattice->get_blocks();

    m_full_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_full_communicator->addPackInfo(
        std::make_shared<PackInfo<PdfField>>(m_pdf_field_id[0]));
    m_full_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_last_applied_force_field_id));
    m_full_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_velocity_field_id));

    m_pdf_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_vel_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_laf_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_pdf_communicator->addPackInfo(
        std::make_shared<PackInfo<PdfField>>(m_pdf_field_id[0]));
    m_vel_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_velocity_field_id));
    m_laf_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_last_applied_force_field_id));

    m_boundary_communicator =
        std::make_shared<BoundaryFullCommunicator>(blocks);
    m_boundary_communicator->addPackInfo(
        std::make_shared<field::communication::BoundaryFlagPackInfo<FlagField>>(
            m_flag_field_id));
    auto boundary_packinfo = std::make_shared<
        field::communication::BoundaryPackInfo<FlagField, BoundaryModel>>(
        m_flag_field_id);
    boundary_packinfo->setup_boundary_handle(m_lattice, m_boundary);
    m_boundary_communicator->addPackInfo(boundary_packinfo);
  }

  /**
   * @brief Set up the communicator used during integration.
   * For color-gradient LB, always uses the generic pack info (no LE boundary).
   */
  void setup_streaming_communicator() {
    auto const setup = [this]<typename PackInfoPdf, typename PackInfoVec>() {
      auto const &blocks = m_lattice->get_blocks();
      m_pdf_streaming_communicator =
          std::make_shared<PDFStreamingCommunicator>(blocks);
      m_pdf_streaming_communicator->addPackInfo(
          std::make_shared<PackInfoPdf>(m_pdf_field_id[0]));
      m_pdf_streaming_communicator->addPackInfo(
          std::make_shared<PackInfoVec>(m_last_applied_force_field_id));
    };
    using FieldTrait = FieldTrait<FloatType, Stencil, Architecture>;
    using PackInfoPdf = FieldTrait::PackInfoStreamingPdf;
    using PackInfoVec = FieldTrait::PackInfoStreamingVec;
    if (m_has_boundaries) {
      setup.template operator()<PackInfo<PdfField>, PackInfoVec>();
    } else {
      setup.template operator()<PackInfoPdf, PackInfoVec>();
    }
  }
};

} // namespace walberla

// Out-of-class template method definitions
#include "LBBoundaryAccessColorGradient.impl.hpp"
#include "LBCollisionSetupColorGradient.impl.hpp"
#include "LBInterpolationColorGradient.impl.hpp"
#include "LBNodeAccessColorGradient.impl.hpp"
#include "LBSliceAccessColorGradient.impl.hpp"
#include "LBVTKColorGradient.impl.hpp"
