/*
 * Copyright (C) 2019-2026 The ESPResSo project
 *
 * This file is part of ESPResSo.
 *
 * ESPResSo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ESPResSo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

/**
 * @file
 * @ref walberla::LBWalberlaImplSingleComponent implements the interface of
 * the single-component LB waLBerla bridge using sweeps generated by lbmpy
 * (see <tt>maintainer/walberla_kernels</tt>).
 */

#include "LBWalberlaCommon.hpp"

#include <blockforest/Initialization.h>
#include <blockforest/StructuredBlockForest.h>
#include <domain_decomposition/BlockDataID.h>
#include <domain_decomposition/IBlock.h>
#include <field/AddToStorage.h>
#include <field/vtk/FlagFieldCellFilter.h>
#include <field/vtk/VTKWriter.h>
#include <stencil/D3Q19.h>
#include <stencil/D3Q27.h>
#include <waLBerlaDefinitions.h>
#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
#include <gpu/AddGPUFieldToStorage.h>
#include <gpu/HostFieldAllocator.h>
#endif

#include "../BoundaryHandling.hpp"
#include "../BoundaryPackInfo.hpp"
#include "../utils/boundary.hpp"
#include "../utils/types_conversion.hpp"
#include "InterpolateAndShiftAtBoundary.hpp"
#include "ResetForce.hpp"
#include "lb_fields.hpp"
#include "lb_kernels.hpp"
#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
#include "lb_fields.cuh"
#include "lb_kernels.cuh"
#endif

#include <walberla_bridge/Architecture.hpp>
#include <walberla_bridge/BlockAndCell.hpp>
#include <walberla_bridge/LatticeWalberla.hpp>
#include <walberla_bridge/lattice_boltzmann/LBWalberlaBase.hpp>
#include <walberla_bridge/lattice_boltzmann/LeesEdwardsPack.hpp>
#include <walberla_bridge/utils/ResourceManager.hpp>
#include <walberla_bridge/walberla_init.hpp>

#include <utils/Vector.hpp>

#include <array>
#include <bitset>
#include <cstddef>
#include <functional>
#include <initializer_list>
#include <limits>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

namespace walberla {

/** @brief Class that runs and controls the single-component LB on waLBerla. */
template <typename FloatType, lbmpy::Arch Architecture>
class LBWalberlaImplSingleComponent
    : public LBWalberlaCommon<
          LBWalberlaImplSingleComponent<FloatType, Architecture>, FloatType,
          Architecture> {
  using Base =
      LBWalberlaCommon<LBWalberlaImplSingleComponent<FloatType, Architecture>,
                       FloatType, Architecture>;
  friend Base;

protected:
  // ---- Types from the mixin (re-export for the .impl.hpp files) ----
  using typename Base::_PdfField;
  using typename Base::_VectorField;
  using typename Base::BlockStorage;
  using typename Base::BoundaryFullCommunicator;
  using typename Base::BoundaryModel;
  using typename Base::GhostComm;
  using typename Base::Kernels;
  using typename Base::PDFStreamingCommunicator;
  using typename Base::RegularFullCommunicator;
  template <class Field>
  using PackInfo = typename Base::template PackInfo<Field>;

  using CollisionModel =
      std::variant<typename Kernels::StreamCollisionModelThermalized,
                   typename Kernels::StreamCollisionModelLeesEdwards>;

public:
  using typename Base::FlagField;
  using typename Base::PdfField;
  using typename Base::ScalarField;
  using typename Base::Stencil;
  using typename Base::StencilFull;
  using typename Base::VectorField;
#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
  using typename Base::GPUField;
  using typename Base::PdfFieldCpu;
  using typename Base::VectorFieldCpu;
#endif
  using Base::get_lattice;

protected:
  // ---- Pull in inherited members so unqualified names resolve ----
  using Base::add_to_storage;
  using Base::derived;
  using Base::FloatType_c;
  using Base::ghost_communication;
  using Base::make_density_interpolation_kernel;
  using Base::make_velocity_interpolation_kernel;
  using Base::zero_centered_to_lb;
  using Base::zero_centered_to_lb_in_place;
  using Base::zero_centered_to_md;
  using Base::zero_centered_to_md_in_place;

  // Data members (from Base)
  using Base::Boundary_flag;
  using Base::m_boundary;
  using Base::m_boundary_communicator;
  using Base::m_density;
  using Base::m_flag_field_id;
  using Base::m_force_to_be_applied_id;
  using Base::m_full_communicator;
  using Base::m_has_boundaries;
  using Base::m_laf_communicator;
  using Base::m_last_applied_force_field_id;
  using Base::m_lattice;
  using Base::m_mpi_cart_comm_observer;
  using Base::m_pdf_communicator;
  using Base::m_pdf_streaming_communicator;
  using Base::m_pending_ghost_comm;
  using Base::m_seed;
  using Base::m_vel_communicator;
  using Base::m_vel_tmp_field_id;
  using Base::m_velocity_field_id;
  using Base::m_zc_to_lb;
  using Base::m_zc_to_md;

protected:
  // ---- Member Variables (leaf-specific) ----

  // Physical parameters
  FloatType m_viscosity; /// kinematic viscosity
  FloatType m_kT;

  // Block data access handles (PDF / temporaries)
  // m_pdf_field_id[0] is the single-component PDF field.
  // The array shape is kept to satisfy LBWalberlaCommon's CRTP access pattern.
  std::array<BlockDataID, 2> m_pdf_field_id;
  std::array<BlockDataID, 2> m_pdf_tmp_field_id;

#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
  std::optional<BlockDataID> m_pdf_cpu_field_id;
  std::optional<BlockDataID> m_vel_cpu_field_id;
#endif

  // collision sweep
  std::shared_ptr<CollisionModel> m_collision_model;

  // force reset sweep + external force handling
  std::shared_ptr<ResetForce<PdfField, VectorField>> m_reset_force;

  // velocity update sweep
  std::shared_ptr<typename Kernels::UpdateVelFromPDF>
      m_update_velocities_from_pdf;

  // Lees-Edwards boundary interpolation
  std::shared_ptr<LeesEdwardsPack> m_lees_edwards_callbacks;
  std::shared_ptr<InterpolateAndShiftAtBoundary<_PdfField, FloatType>>
      m_lees_edwards_pdf_interpol_sweep;
  std::shared_ptr<InterpolateAndShiftAtBoundary<_VectorField, FloatType>>
      m_lees_edwards_vel_interpol_sweep;
  std::shared_ptr<InterpolateAndShiftAtBoundary<_VectorField, FloatType>>
      m_lees_edwards_last_applied_force_interpol_sweep;

#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
  std::shared_ptr<gpu::HostFieldAllocator<FloatType>> m_host_field_allocator;
#endif

public:
  LBWalberlaImplSingleComponent(std::shared_ptr<LatticeWalberla> lattice,
                                std::vector<double> viscosity, double density,
                                bool /* two_component */)
      : Base(lattice, FloatType_c(density)),
        m_viscosity{FloatType_c(viscosity.at(0))}, m_kT(FloatType{0}) {

    auto const &blocks = m_lattice->get_blocks();
    auto const n_ghost_layers = m_lattice->get_ghost_layers();
    if (n_ghost_layers == 0u)
      throw std::runtime_error("At least one ghost layer must be used");

    // Initialize and register fields (must use the "underlying" types)
    m_pdf_field_id[0] = this->template add_to_storage<_PdfField>("pdfs_a");
    m_pdf_tmp_field_id[0] =
        this->template add_to_storage<_PdfField>("pdfs_a_tmp");
    m_last_applied_force_field_id =
        this->template add_to_storage<_VectorField>("force last");
    m_force_to_be_applied_id =
        this->template add_to_storage<_VectorField>("force next");
    m_velocity_field_id =
        this->template add_to_storage<_VectorField>("velocity");
    m_vel_tmp_field_id =
        this->template add_to_storage<_VectorField>("velocity_tmp");

#if defined(__CUDACC__) and defined(WALBERLA_BUILD_WITH_CUDA)
    m_host_field_allocator =
        std::make_shared<gpu::HostFieldAllocator<FloatType>>();
#endif

    // Initialize and register pdf field with zero centered density
    auto pdf_setter = typename Kernels::InitialPDFsSetter(
        m_force_to_be_applied_id, m_pdf_field_id[0], m_velocity_field_id, 1.0);
    for (auto &block : *blocks) {
      pdf_setter(&block);
    }

    // Initialize and register flag field (fluid/boundary)
    m_flag_field_id = field::addFlagFieldToStorage<FlagField>(
        blocks, "flag field", n_ghost_layers);
    // Initialize boundary sweep
    reset_boundary_handling(m_lattice->get_blocks());

    // Set up the communication and register fields
    setup_streaming_communicator();
    setup_full_communicator();

    m_pending_ghost_comm.set();

    // Instantiate the sweep responsible for force double buffering and
    // external forces
    m_reset_force = std::make_shared<ResetForce<PdfField, VectorField>>(
        m_last_applied_force_field_id, m_force_to_be_applied_id);

    // Instantiate velocity update sweep
    m_update_velocities_from_pdf =
        std::make_shared<typename Kernels::UpdateVelFromPDF>(
            m_last_applied_force_field_id, m_pdf_field_id[0],
            m_velocity_field_id);
  }

  ~LBWalberlaImplSingleComponent() override = default;

  // ---- Integration (Core LB Algorithm) ----

  void integrate() override {
    integrate_pull_scheme();
    integrate_vtk_writers();
  }

protected:
  void integrate_vtk_writers() override {
    for (auto const &it : this->m_vtk_auto) {
      auto &vtk_handle = it.second;
      if (vtk_handle->enabled) {
        vtk::writeFiles(vtk_handle->ptr)();
        vtk_handle->execution_count++;
      }
    }
  }

private:
  /**
   * @brief One LB time step using the pull scheme.
   * Sequence: reset forces, stream-collide, communicate PDFs,
   * apply Lees-Edwards interpolation (if active), handle boundaries,
   * update velocity field from PDFs.
   */
  void integrate_pull_scheme() {
    assert(m_mpi_cart_comm_observer.is_valid());
    auto const &blocks = get_lattice().get_blocks();

    // Reset force fields
    integrate_reset_force(blocks);
    // LB stream collide
    integrate_stream_collide(blocks);
    // Mark pending ghost layer updates
    // As pdf and laf are communicated directly afterwards, they are not set
    m_pending_ghost_comm.set(GhostComm::VEL);
    m_pending_ghost_comm.set(GhostComm::LAF);
    m_pdf_streaming_communicator->communicate();
    if (has_lees_edwards_bc()) {
      apply_lees_edwards_pdf_interpolation(blocks);
      apply_lees_edwards_last_applied_force_interpolation(blocks);
    }
    // Handle boundaries
    if (m_has_boundaries) {
      integrate_boundaries(blocks);
    }
    // Update velocities from pdfs
    integrate_update_velocities_from_pdf(blocks);

    if (has_lees_edwards_bc()) {
      apply_lees_edwards_vel_interpolation_and_shift(blocks);
    }
  }

  void integrate_stream_collide(std::shared_ptr<BlockStorage> const &blocks) {
    auto &cm_variant = *m_collision_model;
    for (auto &block : *blocks) {
      auto const block_variant = std::variant<IBlock *>(&block);
      std::visit(m_run_stream_collide_sweep, cm_variant, block_variant);
    }
    if (auto *cm =
            std::get_if<typename Kernels::StreamCollisionModelThermalized>(
                &cm_variant)) {
      cm->setTime_step(cm->getTime_step() + 1u);
    }
  }

  void integrate_reset_force(std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_reset_force)(&block);
  }

  void integrate_boundaries(std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_boundary)(&block);
  }

  void integrate_update_velocities_from_pdf(
      std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_update_velocities_from_pdf)(&block);
  }

private:
  // ---- Collision Model ----

  /**
   * @brief Visitor for dispatching stream-collide sweeps.
   * Handles both thermalized and Lees-Edwards collision models
   * via @c std::visit on the @ref CollisionModel variant.
   */
  class StreamCollideSweepVisitor {
  public:
    using StructuredBlockStorage = LatticeWalberla::Lattice_T;

    void operator()(typename Kernels::StreamCollisionModelThermalized &cm,
                    IBlock *b) {
      cm.configure(m_storage, b);
      cm(b);
    }

    void operator()(typename Kernels::StreamCollisionModelLeesEdwards &cm,
                    IBlock *b) {
      cm.setV_s(static_cast<decltype(cm.getV_s())>(
          m_lees_edwards_callbacks->get_shear_velocity()));
      cm(b);
    }

    StreamCollideSweepVisitor() = default;
    StreamCollideSweepVisitor(std::shared_ptr<StructuredBlockStorage> storage) {
      m_storage = std::move(storage);
    }
    StreamCollideSweepVisitor(std::shared_ptr<StructuredBlockStorage> storage,
                              std::shared_ptr<LeesEdwardsPack> callbacks) {
      m_storage = std::move(storage);
      m_lees_edwards_callbacks = std::move(callbacks);
    }

  private:
    std::shared_ptr<StructuredBlockStorage> m_storage{};
    std::shared_ptr<LeesEdwardsPack> m_lees_edwards_callbacks{};
  };
  StreamCollideSweepVisitor m_run_stream_collide_sweep{};

  /** @brief Relaxation rate omega from kinematic viscosity: 2/(6*nu+1). */
  FloatType shear_mode_relaxation_rate(std::size_t component = 0u) const;
  /**
   * @brief Odd-mode relaxation rate for the magic parameter relation.
   * Ensures optimal bounce-back wall location for the two-relaxation-time
   * model. Default magic number is 3/16.
   */
  FloatType odd_mode_relaxation_rate(
      FloatType shear_relaxation,
      FloatType magic_number = FloatType{3} / FloatType{16}) const;

public:
  void set_collision_model(double kT, unsigned int seed) override;
  void set_collision_model(
      std::unique_ptr<LeesEdwardsPack> &&lees_edwards_pack) override;
  void check_lebc(unsigned int shear_direction,
                  unsigned int shear_plane_normal) const override;

public:
  // ---- Ghost Communication ----

  /**
   * @brief Perform all pending ghost layer updates.
   * Uses a lazy scheme: ghost communications are only executed when
   * they have been marked as pending by a preceding write operation.
   */
  void ghost_communication() override {
    if (!m_pending_ghost_comm.any())
      return;
    assert(m_mpi_cart_comm_observer.is_valid());
    ghost_communication_boundary();
    ghost_communication_pdf();
    ghost_communication_laf();
    ghost_communication_vel();
  }

  void ghost_communication_pdf() override {
    if (m_pending_ghost_comm.test(GhostComm::PDF)) {
      assert(m_mpi_cart_comm_observer.is_valid());
      m_pdf_communicator->communicate();
      if (has_lees_edwards_bc()) {
        auto const &blocks = get_lattice().get_blocks();
        apply_lees_edwards_pdf_interpolation(blocks);
      }
      m_pending_ghost_comm.reset(GhostComm::PDF);
    }
  }

  void ghost_communication_vel() override {
    if (m_pending_ghost_comm.test(GhostComm::VEL)) {
      assert(m_mpi_cart_comm_observer.is_valid());
      m_vel_communicator->communicate();
      if (has_lees_edwards_bc()) {
        auto const &blocks = get_lattice().get_blocks();
        apply_lees_edwards_vel_interpolation_and_shift(blocks);
      }
      m_pending_ghost_comm.reset(GhostComm::VEL);
    }
  }

  void ghost_communication_laf() override {
    if (m_pending_ghost_comm.test(GhostComm::LAF)) {
      assert(m_mpi_cart_comm_observer.is_valid());
      m_laf_communicator->communicate();
      if (has_lees_edwards_bc()) {
        auto const &blocks = get_lattice().get_blocks();
        apply_lees_edwards_last_applied_force_interpolation(blocks);
      }
      m_pending_ghost_comm.reset(GhostComm::LAF);
    }
  }

  void ghost_communication_boundary() {
    if (m_pending_ghost_comm.test(GhostComm::UBB)) {
      assert(m_mpi_cart_comm_observer.is_valid());
      m_boundary_communicator->communicate();
      m_pending_ghost_comm.reset(GhostComm::UBB);
    }
  }

  /** @brief Communicate all fields at once using the D3Q27 stencil. */
  void ghost_communication_full() {
    assert(m_mpi_cart_comm_observer.is_valid());
    m_full_communicator->communicate();
    if (has_lees_edwards_bc()) {
      apply_lees_edwards_interpolation();
    }
    m_pending_ghost_comm.reset(GhostComm::PDF);
    m_pending_ghost_comm.reset(GhostComm::VEL);
    m_pending_ghost_comm.reset(GhostComm::LAF);
  }

private:
  // ---- Lees-Edwards Boundary Conditions ----

  auto has_lees_edwards_bc() const {
    return m_collision_model and
           std::holds_alternative<
               typename Kernels::StreamCollisionModelLeesEdwards>(
               *m_collision_model);
  }

  void apply_lees_edwards_pdf_interpolation(
      std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_lees_edwards_pdf_interpol_sweep)(&block);
  }

  void apply_lees_edwards_vel_interpolation_and_shift(
      std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_lees_edwards_vel_interpol_sweep)(&block);
  }

  void apply_lees_edwards_last_applied_force_interpolation(
      std::shared_ptr<BlockStorage> const &blocks) {
    for (auto &block : *blocks)
      (*m_lees_edwards_last_applied_force_interpol_sweep)(&block);
  }

public:
  void apply_lees_edwards_interpolation() {
    auto const &blocks = get_lattice().get_blocks();
    apply_lees_edwards_pdf_interpolation(blocks);
    apply_lees_edwards_vel_interpolation_and_shift(blocks);
    apply_lees_edwards_last_applied_force_interpolation(blocks);
  }

public:
  // ---- Node & Slice Accessors (by quantity) ----

  // Velocity
  std::optional<Utils::Vector3d>
  get_node_velocity(Utils::Vector3i const &node,
                    bool consider_ghosts = false) const override;
  bool set_node_velocity(Utils::Vector3i const &node,
                         Utils::Vector3d const &v) override;
  std::vector<double>
  get_slice_velocity(Utils::Vector3i const &lower_corner,
                     Utils::Vector3i const &upper_corner) const override;
  void set_slice_velocity(Utils::Vector3i const &lower_corner,
                          Utils::Vector3i const &upper_corner,
                          std::vector<double> const &velocity) override;

  // Density
  std::optional<double>
  get_node_density(Utils::Vector3i const &node,
                   bool consider_ghosts = false) const override;
  bool set_node_density(Utils::Vector3i const &node, double density) override;
  std::vector<double>
  get_slice_density(Utils::Vector3i const &lower_corner,
                    Utils::Vector3i const &upper_corner) const override;
  void set_slice_density(Utils::Vector3i const &lower_corner,
                         Utils::Vector3i const &upper_corner,
                         std::vector<double> const &density) override;

  // Population
  std::optional<std::vector<double>>
  get_node_population(Utils::Vector3i const &node,
                      bool consider_ghosts = false) const override;
  bool set_node_population(Utils::Vector3i const &node,
                           std::vector<double> const &population) override;
  std::vector<double>
  get_slice_population(Utils::Vector3i const &lower_corner,
                       Utils::Vector3i const &upper_corner) const override;
  void set_slice_population(Utils::Vector3i const &lower_corner,
                            Utils::Vector3i const &upper_corner,
                            std::vector<double> const &population) override;

  // Force
  std::optional<Utils::Vector3d>
  get_node_force_to_be_applied(Utils::Vector3i const &node) const override;
  std::optional<Utils::Vector3d>
  get_node_last_applied_force(Utils::Vector3i const &node,
                              bool consider_ghosts = false) const override;
  bool set_node_last_applied_force(Utils::Vector3i const &node,
                                   Utils::Vector3d const &force) override;
  std::vector<double> get_slice_last_applied_force(
      Utils::Vector3i const &lower_corner,
      Utils::Vector3i const &upper_corner) const override;
  void set_slice_last_applied_force(Utils::Vector3i const &lower_corner,
                                    Utils::Vector3i const &upper_corner,
                                    std::vector<double> const &force) override;

  // Pressure tensor
  std::optional<Utils::VectorXd<9>>
  get_node_pressure_tensor(Utils::Vector3i const &node) const override;
  std::vector<double>
  get_slice_pressure_tensor(Utils::Vector3i const &lower_corner,
                            Utils::Vector3i const &upper_corner) const override;

private:
  // ---- Interpolation (position-based access, leaf-specific) ----

  /** @brief Return a B-spline interpolation kernel for force distribution. */
  auto make_force_interpolation_kernel() const;

public:
  bool add_force_at_pos(Utils::Vector3d const &pos,
                        Utils::Vector3d const &force) override;
  void add_forces_at_pos(std::vector<Utils::Vector3d> const &pos,
                         std::vector<Utils::Vector3d> const &forces) override;
  void add_density_weighted_forces_at_pos(
      std::vector<Utils::Vector3d> const &pos,
      std::vector<Utils::Vector3d> const &forces) override;

public:
  // ---- Boundary Handling (leaf-specific helpers) ----

  void reset_boundary_handling(std::shared_ptr<BlockStorage> const &blocks) {
    auto const [lc, uc] = m_lattice->get_local_grid_range(true);
    m_boundary = std::make_shared<BoundaryModel>(
        blocks, m_pdf_field_id[0], m_flag_field_id,
        CellInterval{to_cell(lc), to_cell(uc)});
  }

  void on_boundary_add();

public:
  // ---- Global Reductions & Physical Parameters ----

  // Global pressure tensor
  [[nodiscard]] Utils::VectorXd<9> get_pressure_tensor() const override {
    Matrix3<FloatType> tensor(FloatType{0});
    for (auto const &block : *get_lattice().get_blocks()) {
      auto pdf_field = block.template getData<PdfField>(m_pdf_field_id[0]);
      tensor += lbm::accessor::PressureTensor::reduce(pdf_field, m_density);
    }
    auto const &grid_size = get_lattice().get_grid_dimensions();
    auto const number_of_nodes = Utils::product(grid_size);
    pressure_tensor_correction(tensor);
    return to_vector9d(tensor) * (1. / static_cast<double>(number_of_nodes));
  }

  // Global momentum
  [[nodiscard]] Utils::Vector3d get_momentum() const override {
    Vector3<FloatType> mom(FloatType{0});
    for (auto const &block : *get_lattice().get_blocks()) {
      auto pdf_field = block.template getData<PdfField>(m_pdf_field_id[0]);
      auto force_field =
          block.template getData<VectorField>(m_last_applied_force_field_id);
      mom += lbm::accessor::MomentumDensity::reduce(pdf_field, force_field,
                                                    m_density);
    }
    return to_vector3d(mom);
  }

  void set_viscosity(double viscosity) override {
    m_viscosity = FloatType_c(viscosity);
  }

  [[nodiscard]] double get_viscosity() const override {
    return static_cast<double>(m_viscosity);
  }

  [[nodiscard]] double get_kT() const noexcept override {
    return static_cast<double>(m_kT);
  }

  /**
   * @brief Correction factor for off-diagonal pressure tensor elements.
   * Compensates for the viscosity-dependent error in the non-equilibrium
   * stress: factor = nu / (nu + 1/6).
   */
  FloatType pressure_tensor_correction_factor() const {
    return m_viscosity / (m_viscosity + FloatType{1} / FloatType{6});
  }

  void pressure_tensor_correction(Matrix3<FloatType> &tensor) const {
    auto const revert_factor = pressure_tensor_correction_factor();
    for (auto const i : {1u, 2u, 3u, 5u, 6u, 7u}) {
      tensor[i] *= revert_factor;
    }
  }

  void pressure_tensor_correction(std::span<FloatType, 9ul> tensor) const {
    auto const revert_factor = pressure_tensor_correction_factor();
    for (auto const i : {1u, 2u, 3u, 5u, 6u, 7u}) {
      tensor[i] *= revert_factor;
    }
  }

public:
  // ---- File I/O ----

  void register_vtk_field_filters(walberla::vtk::VTKOutput &vtk_obj) override {
    field::FlagFieldCellFilter<FlagField> fluid_filter(m_flag_field_id);
    fluid_filter.addFlag(Boundary_flag);
    vtk_obj.addCellExclusionFilter(fluid_filter);
  }

  void register_vtk_field_writers(walberla::vtk::VTKOutput &vtk_obj,
                                  LatticeModel::units_map const &units,
                                  int flag_observables) override;

protected:
  // ---- Communicator setup (uses leaf-only PDF field IDs) ----

  /**
   * @brief Set up D3Q27 communicators for full ghost layer updates.
   * Creates per-field communicators (PDF, velocity, last-applied force)
   * as well as a combined communicator and the boundary communicator.
   */
  void setup_full_communicator() {
    auto const &blocks = m_lattice->get_blocks();

    m_full_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_full_communicator->addPackInfo(
        std::make_shared<PackInfo<PdfField>>(m_pdf_field_id[0]));
    m_full_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_last_applied_force_field_id));
    m_full_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_velocity_field_id));

    m_pdf_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_vel_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_laf_communicator = std::make_shared<RegularFullCommunicator>(blocks);
    m_pdf_communicator->addPackInfo(
        std::make_shared<PackInfo<PdfField>>(m_pdf_field_id[0]));
    m_vel_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_velocity_field_id));
    m_laf_communicator->addPackInfo(
        std::make_shared<PackInfo<VectorField>>(m_last_applied_force_field_id));

    m_boundary_communicator =
        std::make_shared<BoundaryFullCommunicator>(blocks);
    m_boundary_communicator->addPackInfo(
        std::make_shared<field::communication::BoundaryFlagPackInfo<FlagField>>(
            m_flag_field_id));
    auto boundary_packinfo = std::make_shared<
        field::communication::BoundaryPackInfo<FlagField, BoundaryModel>>(
        m_flag_field_id);
    boundary_packinfo->setup_boundary_handle(m_lattice, m_boundary);
    m_boundary_communicator->addPackInfo(boundary_packinfo);
  }

  /**
   * @brief Set up the communicator used during integration.
   * Uses optimized streaming pack info when neither boundaries nor
   * Lees-Edwards boundary conditions are active; falls back to the
   * generic pack info otherwise.
   */
  void setup_streaming_communicator() {
    auto const setup = [this]<typename PackInfoPdf, typename PackInfoVec>() {
      auto const &blocks = m_lattice->get_blocks();
      m_pdf_streaming_communicator =
          std::make_shared<PDFStreamingCommunicator>(blocks);
      m_pdf_streaming_communicator->addPackInfo(
          std::make_shared<PackInfoPdf>(m_pdf_field_id[0]));
      m_pdf_streaming_communicator->addPackInfo(
          std::make_shared<PackInfoVec>(m_last_applied_force_field_id));
    };
    using FieldTrait = FieldTrait<FloatType, Stencil, Architecture>;
    using PackInfoPdf = FieldTrait::PackInfoStreamingPdf;
    using PackInfoVec = FieldTrait::PackInfoStreamingVec;
    if (m_has_boundaries or (m_collision_model and has_lees_edwards_bc())) {
      setup.template operator()<PackInfo<PdfField>, PackInfoVec>();
    } else {
      setup.template operator()<PackInfoPdf, PackInfoVec>();
    }
  }
};

} // namespace walberla

// Out-of-class template method definitions
#include "LBBoundaryAccessSingleComponent.impl.hpp"
#include "LBCollisionSetupSingleComponent.impl.hpp"
#include "LBInterpolationSingleComponent.impl.hpp"
#include "LBNodeAccessSingleComponent.impl.hpp"
#include "LBSliceAccessSingleComponent.impl.hpp"
#include "LBVTKSingleComponent.impl.hpp"
